### ISSUE TITLE
idk whats wrong

### ISSUE THREAD

**Issue by Exoduf0** [saaiful/socks5#1]
root@4t7s:~# sudo bash socks5.sh
Please enter the username for the socks5 proxy:
patryk
Please enter the password for the socks5 proxy:
Hit:1 http://ubuntu-archive.mirror.serveriai.lt jammy InRelease
Hit:2 http://ubuntu-archive.mirror.serveriai.lt jammy-updates InRelease
Hit:3 http://ubuntu-archive.mirror.serveriai.lt jammy-security InRelease
Hit:4 http://ubuntu-archive.mirror.serveriai.lt jammy-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
178 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dante-server is already the newest version (1.4.2+dfsg-7build4).
0 upgraded, 0 newly installed, 0 to remove and 178 not upgraded.
Synchronizing state of danted.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable danted
root@4t7s:~# curl -x socks5://####:####@195.181.245.80:1080 https://ipconfig.me
curl: (7) Failed to connect to 195.181.245.80 port 1080 after 0 ms: Connection refused

**Comment by theurzil** [comment]
did you check if there is there is an issue with the installation or configuration of the dante-serve ??

**Comment by saaiful** [comment]
Check If you have firewale enabled (if firewale is active, allow port 1080) , also sometime server providers blocks few common ports.

**Comment by thanhchunghti** [comment]
Me to, curl: (7) Failed to connect to 45.76.123.93 port 1080 after 0 ms: Connection refused
Can you help me, pls?

**Comment by saaiful** [comment]
Please ensure that your Ubuntu firewall is configured to allow traffic on port 1080. If you're not using UFW (Uncomplicated Firewall), you can use the following iptables command to allow incoming traffic on port 1080:
```bash
sudo iptables -A INPUT -p tcp --dport 1080 -j ACCEPT
````
If you're using UFW, you can achieve the same result with the following command:

```bash
sudo ufw allow 1080/tcp
```
If UFW is not enabled, please contact your server provider and request them to open port 1080 for you.

**Comment by saaiful** [comment]
Also updated the bash code to check for UFW and IPTABLE.

**Comment by C0la149** [comment]
curl: (7) Failed to connect to 109.120.184.192 port 1080 after 0 ms: Couldn't connect to server

**Comment by C0la149** [comment]
root@erratic-creator:~# sudo iptables -A INPUT -p tcp --dport 1080 -j ACCEPT
root@erratic-creator:~# sudo ufw allow 1080/tcp
Skipping adding existing rule
Skipping adding existing rule (v6)
root@erratic-creator:~# sudo ufw allow 1080/tcp
Skipping adding existing rule
Skipping adding existing rule (v6)
root@erratic-creator:~# curl -x socks5://vpn:vpn228@proxy_server_ip:1080 https://ifconfig.me
curl: (6) Could not resolve host: proxy_server_ip
root@erratic-creator:~# curl -x socks5://admin:228admin@109.120.184.192:1080 https://ifconfig.me
curl: (7) Failed to connect to 109.120.184.192 port 1080 after 0 ms: Couldn't connect to server
root@erratic-creator:~#
